### ISSUE TITLE
install to raspberry pi for non computer literate person 

### ISSUE THREAD

**Issue by leesoyavh** [thirtythreeforty/neolink#176]
hello

I tried following this https://github.com/thirtythreeforty/neolink/issues/73

I installed point 0 - install dependencies, then at get binary; I lost it

I'm sorry to be stupid here :)

can any one help please?

with this add on soon be available through the plug ins search bar in home bridge soon as that I can handle :)

any help though to push through would be great

**Comment by QuantumEntangledAndy** [comment]
You can find the binary in the link I gave you in the previous issue #175 you raised [here](https://nightly.link/thirtythreeforty/neolink/workflows/build/master/release-armhf-buster.zip)

You could do it from the terminal on the raspberry pi with this

```bash
curl -LJO 'https://nightly.link/thirtythreeforty/neolink/workflows/build/master/release-armhf-buster.zip'
```

Then extract it

```bash
unzip release-armhf-buster.zip
```

Then copy it

```bash
cp neolink /usr/local/bin/neolink
```

Then chmod it

```bash
chmod +x /usr/local/bin/neolink
```

The binary is now installed.... But your job is not over since you need it for home assistant.

Before home assistant though you should get is setup for just ffplay or somethink.

Make a `config.toml` with your configuration and test it works


https://user-images.githubusercontent.com/13386481/125151895-afb07d80-e173-11eb-9f12-4158916bbda4.mp4

**Comment by QuantumEntangledAndy** [comment]
Were you able to resolve this? If so can I close this issue?

**Comment by thirtythreeforty** [comment]
If you have other questions, feel free to make a Discussion. Gonna go ahead and resolve this, thanks for flying Neolink!
