### ISSUE TITLE
NVR-7400 Help

### ISSUE THREAD

**Issue by tjpoddar** [thirtythreeforty/neolink#250]
For Neolink with Swann cameras I have tested:
NHD-818 - Works (Firmware 170518)
NHD-805 - Does not work
NHD-806 - Does not work
NVR-7400 - Works (Reolink Firmware 190823)

805/806 have very similar BC media format as 818. Same 00dc, 01dc BC headers etc.
All are h264 video. 818 has adpcm audio, 805/806 have no audio.
I no longer actually use my 805 or 806 cameras. They are just in storage now.
I had a quick look in a packet capture and the BC protocol looks similar but I have no interest in support due their age and not even using them any more.

"Hardware Ver: IPC_36S8M
Config Ver: v2.0.0.0
Firmware Ver 1029_16061700"
That looks exactly like the other BC products. Eg NHD-818 is IPC_388M, same config ver and same firmware version format.

I believe the Swann BC family is:
NVR-7072, NVR-7085, NVR-7285, NVR-7300, NVR-7400
NHD-805, NHD-806, NHD-810, NHD-811, NHD-815, NHD-815AF, NHD-816, NHD-817, NHD-818, NHD-819
https://www.swann.com/media/wysiwyg/docs/swann-camera-compatibility.pdf

_Originally posted by @twistedddx in https://github.com/thirtythreeforty/neolink/issues/77#issuecomment-698227271_

**Comment by tjpoddar** [comment]
I was trying to configure my NVR-7400, and was hoping you could provide some pointers on what needs to be done. I see you managed to get the NVR working with NHD-818 cams, and I believe the config files should be largely the same for the NHD-819s I have. I'd appreciate any help!

**Comment by twistedddx** [comment]
I have not tested Neolink with Swanns official NVR-7400 firmware.
It may work but I have not tested.

My Swann NVR-7400 was running Reolinks RLN8-410 H3MB02 firmware when I connected to it with Neolink.

If Neolink does support your device all you do in the Neolink config is point to the NVR IP for each camera and you can use the channel_id to specify the NVR channel 0 through 7 for the connected cameras.
Or if the cameras are reachable on your network, Neolink can just direct connect to the individual camera IP's.
If you connect the cameras to the NVR POE ports you can only connect to the NVR IP using the channel_id and not contact the cameras IP directly.

By default Neolink connects both high res and low res streams per camera and logs in per "camera". Both of these can cause resource issues for the NVR.
For testing add 1 camera at a time to the config and test.
In the config define what stream you actually want per camera to reduce the amount of streams open.
I have never been able to get Neolink to connect to 8 cameras on an NVR at once due to Neolink not exactly replicating the official clients behaviour and NVR resource limits.

Neolink was made to allow RTSP for devices that lack that support.
I think the official Swann NVR firmware and certainly Reolink NVR firmware does support RTSP.
This means there is less reasons to use Neolink if you continue to use the NVR.
Neolink NVR support exists mostly because it was easy to add and may assist users to test using Neolink.
It is unlikely you would permanently use Neolink with the NVR.



Regarding Reolink RLN8-410 H3MB02 firmware on a Swann NVR-7400:
Years ago I was checking the firmwares and it appeared the hardware/firmware from Swann and Reolink were extremely similar.
Then I closed my eyes, crossed my fingers and uploaded the Reolink firmware to my Swann device.
There was a high risk this could have destroyed my NVR, but in my case it did not.
I reported this to other users and several others were able to move their units to Reolink firmware also.

I have not successfully switched any camera firmware from Swann to Reolink, I have bricked one Swann camera trying.

The Reolink website has version v2.0.0.4725_1724 for RLN8-410 H3MB02.
My NVR-7400 was flashed to the current Reolink firmware at the time and then updated as firmware was released all the way up to the latest v2.0.0.4725_1724.
It is entirely untested if my unit would have survived going from Swann 7400 to Reolinks latest.

Flashing firmware not intended for a device is extremely risky and will most the time lead to a device that no longer functions.

**Comment by tjpoddar** [comment]
@twistedddx Thank you so much for the help! I was able to flash the latest Reolink firmware onto my NVR and expose the RTSP streams! Great to have the functionality built into the NVR rather than running Neolink externally. Once again I (and others who may see this thread) greatly appreciate your help!

**Comment by twistedddx** [comment]
Great to hear.

Things to know for anyone else that may find this thread:
I believe the default password for cameras has changed over time from 1234, 12345, 123456 etc.
New firmware may default to a newer password and require manual entry of the password for your particular camera.
New Reolink firmware works best with new Reolink client software.
Some users have reported issues with the config for the HDMI port being incompatible until changed after a firmware flash. Be prepared to use VGA port if required.
