### ISSUE TITLE
Provide ARMv6 and ARMv7 Linux builds

### ISSUE THREAD

**Issue by thirtythreeforty** [thirtythreeforty/neolink#27]
Many people want to use Neolink on a Raspberry Pi. This is perfectly feasible. However, it would take a long time to compile. Instead, provide a cross-compiled prebuilt for ARM.

**Comment by Riza-Aslan** [comment]
I've used the Docker image for some time now and experienced very bad wifi issues. I have four E1 cams and couldn't get all of them to work. Only 1 or 2 were working and the log was full with timeouts and reconnects from all cams. And then my whole wifi network stopped working. I could connect with my smartphone, but had no more access to other local devices or the internet. I think there was too much communication between neolink and my four Reolink E1 wifi cams. I had now the idea to configure a raspberry pi 3 as an access point and connect my E1 cams to it, seperated from my main wifi. I could install neolink on this AP, and bind the wifi interface to neolink. What do you think? Do you see any other issues then?

**Comment by thirtythreeforty** [comment]
Yep, definitely make sure you have enough bandwidth. You can use the Reolink app or PC program to configure the video streams to use a lower quality if you have too many. Highly recommend Ethernet for every hop from the cameras.

**Comment by DanieleQ97** [comment]
I've compiled neolink on a Raspberry.
At first, I had some problem, but only because the version of rust in the raspbian repositories is hugely outdated.
After getting rid of it and installing rustup, everything went smoothly. Just some missing dependencies easily fixed.

About providing ARMv6 and ARMv7 pre-built binaries, if I'm not wrong, only Raspberry gen 1 and Zero use ARMv6. All the other should be on ARMv7.
I don't think there will be many Raspberry Zero running neolink out there. And probably even less first-gen boards: I own one of them and, even if are still supported (in theory), I rarely end up using it because of all the headaches setting it up.

You can probably just go with ARMv7. If someone really want to resurrect a very old Pi found in the back of a drawer they can just compile it as I've done.

**Comment by thirtythreeforty** [comment]
Yep, that's a good point. Although, if I get ARM7 cross-build working, it's probably just a flag change to also build ARM6.

**Comment by QuantumEntangledAndy** [comment]
I was thinking about this too since compling on my pi takes ages. Although I didn't have (too) outdated gstreamer libs. Perhaps because I'm using buster os.

This may be of help: [guide on cross compiling rust for arm](https://medium.com/@wizofe/cross-compiling-rust-for-arm-e-g-raspberry-pi-using-any-os-11711ebfc52b)

**Comment by jlg89** [comment]
> I've compiled neolink on a Raspberry.

I've been trying to make this happen all day, with rust installed straight from sh.rustup.rs. The gstreamer stuff is all too old, and my google-fu is failing me. I really want to run neolink on my RPi HOOBS server.

So...yeah, having an ARMv7 binary would be a Very Nice Thing.

**Comment by thirtythreeforty** [comment]
Whoops, I've been neglecting #40 a bit too long. I'll get it merged and @jlg89 hopefully you can have some RPi prebuilts.

**Comment by DanieleQ97** [comment]
@jlg89 Until @QuantumEntangledAndy pull request is accepted you can download the prebuilt binary from his github: https://github.com/QuantumEntangledAndy/neolink/actions/runs/186915887
But if gstreamer and other libraries are too old to compile I suspect you may have some headache also running prebuilt binaries.

**Comment by QuantumEntangledAndy** [comment]
It requires gstreamer>=1.8. The first os for that is stretch so if your running pre-stretch you may want to consider upgrading.

**Comment by jlg89** [comment]
I was able to get gstreamer and gst-rtsp-server updated to versions that neolink seems to be happy with. It's currently compiling, and really chewing up the CPU doing it.

**Comment by thirtythreeforty** [comment]
Try downloading the prebuilt I linked in the PR
