### ISSUE TITLE
Reolink Argus Pro support

### ISSUE THREAD

**Issue by mas0nwest** [thirtythreeforty/neolink#273]
\\haven't tried it myself, just asking because the Argus Pro isn't under Supported cameras//

**Comment by BeanBagKing** [comment]
Not sure exactly what mas0nwest is looking for. Direct streaming for the Argus Pro does work, at least for me. However, that isn't really practical for most purposes, as it will quickly eat the battery. I do wish there was better integration with the PIR sensor, either to only stream when motion is detected (not sure if that's possible or feasible) or let the camera record to the SD card and then pick that file up and replay it over RTSP (same idea, slight delay, lets the camera work with BlueIris and the like).

Related to https://github.com/thirtythreeforty/neolink/issues/248 ?

**Comment by QuantumEntangledAndy** [comment]
We have a PR that will only stream when motion or a client is connected but it doesn't help too much with the battery because it only works if we maintain the connection. There are some ideas to leverage the email settings so that neolink connects when it receives an email from the camera but there's no one working on that idea right now.

**Comment by BeanBagKing** [comment]
I feel like picking up files from the SD card is going to be the best option, regardless of how the connection is triggered. I'm not sure if Reolink sends the email at the start or the end of the motion, but either way, with the delay between sending the email, receiving it, and triggering the stream start, the motion may very well already have passed. There's also push alerts available on the cameras, which might have a little less latency than email, but would still probably suffer the same problems.

I realize the downside to pulling from the SD card is going to be that, no matter what, it isn't a real-time stream, and thus any recording is going to be offset by that much time. In other words, without being able to initiate the connection on the camera's side, the options seem to be:

1. Drain the battery with a constant connection
2. Trigger real time streaming on a push alert or email, potentially missing the actual motion event
3. Playback the actual motion video file, but not get the stream as it's actually happening.

Of those, I would pick 3 myself. Ideally using the email/push notification to know when to pick up files so the delay is only a short time. However, I would also settle for a periodic check for new files (e.g. every XX minutes, poll the camera for new files). My offer to send a camera for testing/development still stands if you're interested and believe it might help.

**Comment by QuantumEntangledAndy** [comment]
Id probably implement all three methods and leave it for the user to decide.

I have looked into the sd card protocol and thought about how to grab the data as a fuse mount. But I'll probably implement 2 next just because it's the lower hanging fruit see how that works then get 3 out when the sd card protocol is fully reversed engineered.

The camera offer is tempting but I live in Asia so after shipping and tax it's probably not worth it :(. Anyways I can do all of this stuff on my E1 just can't test the effect on the battery myself.
