### ISSUE TITLE
Question: How can I reduce frequent "Error streaming from camera..." errors?

### ISSUE THREAD

**Issue by ctrager** [thirtythreeforty/neolink#48]
In your experience or others' experience, if I'm seeing these errors a lot (one per minute or even several per minute), is that because my home WIFI network is shaky?  Is there a way I can configure the camera or neolink to be more steady?

**Comment by hh1209** [comment]
I have found that the latest version of camera firmware works the best with neolink. I used to get retries fairly regularly with all my cameras hard wired until I updated my cameras to the latest firmware.

If you've already updated your cameras it may just be your shaky wifi network

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ctrager** [comment]
I don't see a way of updating the firmware of my E1 using the Android app or a web browser (that's not your problem - I'm contacting Reolink), but here's some info.  When I view the live feed via my Android app, the timestamp watermark updates smoothly second by second, 1, 2, 3...etc.  When I run neolink and then view the stream using VLC, the timestamp stops, then skips 1, 2.......5, 6. 

That makes me think that the network is okay.

I thought, maybe my computer is too slow?  (Slower than my phone???) but system monitor shows CPU usage is under 10%.

**Comment by thirtythreeforty** [comment]
So, a few things here.

I can assure you that your computer is not too slow for Neolink. It's a glorified translator and doesn't really do anything other than copying video data around. It could run on a potato.

It's *possible* (although very unlikely) that your computer is too slow for rendering the video in VLC.  Since it's an E1, that's a 1080p stream I think, and if you don't have trouble watching YouTube in 1080p then playing this video should work fine.

Let me ask you this - are you connecting Neolink and the phone simultaneously? I'd say the most likely scenario is that the simultaneous stream to your phone and to your laptop overwhelms your Wi-Fi bandwidth.  If you kill the stream to the phone, does the stream in VLC stabilize?

Another possibility is that VLC doesn't like the stream because it has extra garbage in it (see #50).

**Comment by ctrager** [comment]
I still have the problem even when my phone is not connected. But.... I have other cameras on the network (that I'm not connecting to). I will try unplugging them to see if that makes a difference, and/or maybe I'll educate myself on how to look at overall network load.
I don't have trouble watching Youtube/Netflix/whatever on my laptop. 
I was just using VLC for testing but my main goal is to use python and opencv to analyze the stream. I'm doing that just fine with an Amcrest camera and its RTSP stream. But I read some articles about smoother performance by using multiple threads, one to just read the stream itself and another to do whatever analysis, so I'm going to try that.

But... I am

**Comment by ctrager** [comment]
I updated my firmware and performance seems a lot better, so thanks.
